default_language_version:
  python: python3.12

repos:
  - repo: local
    hooks:
      - id: precommit_mypy_deps_update
        name: precommit_mypy_deps_update
        entry: ./precommit_mypy_deps_update
        language: python
        files: pyproject.toml
        fail_fast: true
        verbose: true
        additional_dependencies:
          - poetry (>=1.8.3)
          - ruamel.yaml (>=0.18.6)

  - repo: https://github.com/psf/black
    rev: 24.3.0
    hooks:
      - id: black
        args:
          - --check
          - --diff

  - repo: https://github.com/PyCQA/isort
    rev: 5.13.2
    hooks:
      - id: isort
        args:
          - --check-only
          - --diff

  - repo: https://github.com/PyCQA/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
        additional_dependencies:
          - Flake8-pyproject==1.2.3


  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.2
    hooks:
      - id: mypy
        additional_dependencies:
          - black (>=24.3.0,<25.0.0)
          - isort (>=5.13.2,<6.0.0)
          - mypy (>=1.11.0,<1.12.0)
          - flake8 (>=7.0.0,<8.0.0)
          - flake8-pyproject (>=1.2.3,<2.0.0)
          - django-stubs (>=5.0.0,<5.1.0)
          - pdbpp (>=0.10.3,<0.11.0)
          - factory-boy (>=3.3.0,<4.0.0)
          - pytest (>=8.2.0,<9.0.0)
          - pytest-django (>=4.8.0,<5.0.0)
          - ipython (>=8.24.0,<9.0.0)
          - django (>=5.0.3,<5.1.0)
          - environs (>=11.0.0,<12.0.0)
          - cryptography (>=43.0.1,<44.0.0)
          - django-htmx (>=1.17.3,<2.0.0)
          - daphne (>=4.1.0,<5.0.0)
          - whitenoise (>=6.6.0,<7.0.0)
          - sentry-sdk[django] (>=1.44.1,<2.0.0)
          - django-prometheus (>=2.3.1,<3.0.0)
          - prometheus-client (>=0.20.0,<0.21.0)
          - apscheduler (>=3.10.4,<4.0.0)
          - openai (>=1.42.0,<2.0.0)
          - pillow (>=10.4.0,<11.0.0)
          - tiktoken (>=0.7.0,<0.8.0)
          - tekore @ git+https://github.com/ch00k/tekore
          - django-ipware (>=7.0.1,<8.0.0)
          - django-q2 (>=1.7.3,<2.0.0)
