default_language_version:
  python: python3.12

repos:
  - repo: local
    hooks:
      - id: precommit_mypy_deps_update
        name: precommit_mypy_deps_update
        entry: ./precommit_mypy_deps_update
        language: python
        files: pyproject.toml
        fail_fast: true
        verbose: true
        additional_dependencies:
          - poetry (>=1.8.3)
          - ruamel.yaml (>=0.18.6)

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.6
    hooks:
      - id: ruff
      - id: ruff-format

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.19.1
    hooks:
      - id: pyupgrade
        args: [--py312-plus]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.15.0
    hooks:
      - id: mypy
        additional_dependencies:
          - ipython (>=8.24.0,<9.0.0)
          - pdbpp (>=0.10.3,<0.11.0)
          - mypy (>=1.15,<1.16)
          - django-stubs (>=5.1,<5.2)
          - factory-boy (>=3.3.0,<4.0.0)
          - pytest (>=8.2.0,<9.0.0)
          - pytest-django (>=4.8.0,<5.0.0)
          - pyupgrade (>=3.19.0,<4.0.0)
          - django (>=5.1,<5.2)
          - environs (>=11.0.0,<12.0.0)
          - cryptography (>=43.0.1,<44.0.0)
          - django-htmx (>=1.17.3,<2.0.0)
          - whitenoise (>=6.6.0,<7.0.0)
          - sentry-sdk[django] (>=1.44.1,<2.0.0)
          - django-prometheus (>=2.3.1,<3.0.0)
          - prometheus-client (>=0.20.0,<0.21.0)
          - apscheduler (>=3.10.4,<4.0.0)
          - openai (>=1.42.0,<2.0.0)
          - pillow (>=10.4.0,<11.0.0)
          - tiktoken (>=0.7.0,<0.8.0)
          - django-ipware (>=7.0.1,<8.0.0)
          - django-q2 (>=1.7.3,<2.0.0)
          - lxml (>=5.3.0,<6.0.0)
          - thefuzz (>=0.22.1,<0.23.0)
          - django-dirtyfields (>=1.9.3,<2.0.0)
          - pytest-asyncio (>=0.24.0,<0.25.0)
          - unidecode (>=1.3.8,<2.0.0)
          - country-converter (>=1.2,<2.0)
          - json-log-formatter (>=1.1,<2.0)
          - daphne (>=4.1.2,<5.0.0)
          - django-hosts (>=6.0,<7.0)
          - tekore (>=6.0.0,<7.0.0)
