default_language_version:
  python: python3.12

repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.0
    hooks:
      - id: ruff-check
        args:
          - --fix
      - id: ruff-format

  - repo: https://github.com/djlint/djLint
    rev: v1.36.4
    hooks:
      - id: djlint-reformat-django
      #- id: djlint-django

  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: uv run mypy
        args:
          - --config-file
          - pyproject.toml
        verbose: true
        language: system
        types:
          - python
