x-image: &image
  image: mottle:latest

x-env: &env
  PYTHONPATH: /app/mounted
  ALLOWED_HOSTS: 127.0.0.1,localhost,mottle-dev.it,s.mottle-dev.it
  URLSHORTENER_BASE_URL: http://s.mottle-dev.it:65534
  CSRF_TRUSTED_ORIGINS: http://127.0.0.1,http://localhost
  SECRET_KEY: ${SECRET_KEY:-foobar}
  DATABASE_FILE: /app/database/db.sqlite3
  DATABASE_FILE_TASKS: /app/database/tasks.sqlite3
  SPOTIFY_CLIENT_ID: ${SPOTIFY_CLIENT_ID}
  SPOTIFY_CLIENT_SECRET: ${SPOTIFY_CLIENT_SECRET}
  SPOTIFY_REDIRECT_URI: ${SPOTIFY_REDIRECT_URI:-http://mottle-dev.it:65534/callback/}
  SPOTIFY_TOKEN_ENCRYPTION_KEYS: ${SPOTIFY_TOKEN_ENCRYPTION_KEYS}
  MAILERSEND_API_TOKEN: ${MAILERSEND_API_TOKEN}
  MAIL_FROM_EMAIL: ${MAIL_FROM_EMAIL}
  MAIL_FROM_NAME: ${MAIL_FROM_NAME}
  OPENAI_API_KEY: ${OPENAI_API_KEY}
  OPENAI_IMAGES_DUMP_DIR: /images_dump/
  BRIGHTDATA_PROXY_ADDRESS: ${BRIGHTDATA_PROXY_ADDRESS}
  BRIGHTDATA_PROXY_USERNAME: ${BRIGHTDATA_PROXY_USERNAME}
  BRIGHTDATA_PROXY_PASSWORD: ${BRIGHTDATA_PROXY_PASSWORD}
  #SENTRY_DSN: ${SENTRY_DSN}
  #SENTRY_ENVIRONMENT: ${SENTRY_ENVIRONMENT}

name: mottle_dev
services:
  migrate:
    profiles:
      - default
    <<:
      - *image
    environment:
      <<: *env
    command: bash -c "./manage.py migrate --database default && ./manage.py migrate --database tasks"
    volumes:
      - ./runtime_data/database:/app/database
      - .:/app/mounted
    working_dir: /app/mounted

  web:
    profiles:
      - default
    <<:
      - *image
    environment:
      <<: *env
      DJANGO_SETTINGS_MODULE: mottle.settings
    labels:
      - prometheus.scrape-port=65534
    command: ./manage.py runserver 0.0.0.0:65534
    volumes:
      - ./runtime_data/database:/app/database
      - .:/app/mounted
    working_dir: /app/mounted
    ports:
      - 127.0.0.1:65534:65534
    stdin_open: true
    tty: true
    depends_on:
      migrate:
        condition: service_completed_successfully

  scheduler:
    profiles:
      - scheduler
    <<:
      - *image
    environment:
      <<: *env
      DJANGO_SETTINGS_MODULE: mottle.settings
    labels:
      - prometheus.scrape-port=10001
    command: python ./scheduler/run.py 0.0.0.0 10001
    volumes:
      - ./runtime_data/database:/app/database
      - .:/app/mounted
    working_dir: /app/mounted
    depends_on:
      migrate:
        condition: service_completed_successfully

  taskrunner_default:
    profiles:
      - taskrunner
    <<:
      - *image
    environment:
      <<: *env
      DJANGO_SETTINGS_MODULE: mottle.settings
      Q_CLUSTER_NAME: default
      PROMETHEUS_MULTIPROC_DIR: /tmp/prometheus_multiproc_dir
    labels:
      - prometheus.scrape-port=10002
    command: python ./taskrunner/run.py 0.0.0.0 10002
    volumes:
      - ./runtime_data/database:/app/database
      - ./runtime_data/images_dump:/images_dump
      - .:/app/mounted
    working_dir: /app/mounted
    depends_on:
      migrate:
        condition: service_completed_successfully

  taskrunner_long_running:
    profiles:
      - taskrunner
    <<:
      - *image
    environment:
      <<: *env
      DJANGO_SETTINGS_MODULE: mottle.settings
      Q_CLUSTER_NAME: long_running
      PROMETHEUS_MULTIPROC_DIR: /tmp/prometheus_multiproc_dir
    labels:
      - prometheus.scrape-port=10003
    command: python ./taskrunner/run.py 0.0.0.0 10003
    volumes:
      - ./runtime_data/database:/app/database
      - .:/app/mounted
    working_dir: /app/mounted
    depends_on:
      migrate:
        condition: service_completed_successfully
