x-env: &env
  environment:
    SECRET_KEY: ${SECRET_KEY}
    DATABASE_FILE: /database/db.sqlite3
    STATIC_ROOT: /static/
    SPOTIFY_CLIENT_ID: ${SPOTIFY_CLIENT_ID}
    SPOTIFY_CLIENT_SECRET: ${SPOTIFY_CLIENT_SECRET}
    SPOTIFY_REDIRECT_URI: ${SPOTIFY_REDIRECT_URI}

services:
  collectstatic:
    <<: *env
    image: mottle
    command: /src/manage.py collectstatic --noinput
    volumes:
      - ./static:/static

  migrate:
    <<: *env
    image: mottle
    command: /src/manage.py migrate
    volumes:
      - ./database:/database

  web:
    <<: *env
    image: mottle
    command: daphne --bind 0.0.0.0 --port ${PORT} mottle.asgi:application
    volumes:
      - ./static:/static
      - ./database:/database
    ports:
      - 0.0.0.0:${PORT}:${PORT}
    depends_on:
      migrate:
        condition: service_completed_successfully
