#!/usr/bin/env python

import sys
from pathlib import Path

from poetry.core.factory import Factory
from ruamel.yaml import YAML


def main() -> int:
    yaml = YAML()
    yaml.indent(mapping=2, sequence=4, offset=2)

    precommit_config_file = Path.cwd() / ".pre-commit-config.yaml"
    precommit_config = yaml.load(precommit_config_file)

    factory = Factory()
    poetry = factory.create_poetry(Path.cwd())
    pkg = poetry.package

    groups = sorted(pkg.dependency_group_names())

    deps = [*tuple(d.to_pep_508() for g in groups for d in pkg.dependency_group(g).dependencies)]

    for repo in precommit_config["repos"]:
        for hook in repo["hooks"]:
            if hook["id"] == "mypy":
                hook["additional_dependencies"] = deps

    yaml.dump(precommit_config, precommit_config_file)

    return 0


if __name__ == "__main__":
    sys.exit(main())
