[tool.poetry]
name = "mottle"
version = "0.18.1"
description = "Missing spotify features"
authors = ["Andrii Yurchuk <ay@mntw.re>"]
readme = "README.md"
packages = [
  { include = "mottle" },
  { include = "web" },
  { include = "scheduler" },
]

[tool.poetry.dependencies]
python = "^3.12"
django = "^5.0.3"
environs = "^11.0.0"
django-htmx = "^1.17.3"
daphne = "^4.1.0"
whitenoise = "^6.6.0"
tekore = "^5.4.0"
sentry-sdk = { extras = ["django"], version = "^1.44.1" }
django-prometheus = "^2.3.1"
prometheus-client = "^0.20.0"
apscheduler = "^3.10.4"
openai = "^1.42.0"
pillow = "^10.4.0"
tiktoken = "^0.7.0"
django-q2 = "^1.6.2"

[tool.poetry.group.dev.dependencies]
black = "^24.3.0"
isort = "^5.13.2"
mypy = "^1.9.0"
flake8 = "^7.0.0"
flake8-pyproject = "^1.2.3"
django-stubs = "^5.0.0"
pdbpp = "^0.10.3"
factory-boy = "^3.3.0"
pytest = "^8.2.0"
pytest-django = "^4.8.0"
ipython = "^8.24.0"

[tool.poetry.scripts]
scheduler = 'scheduler.run:main'
taskrunner = 'taskrunner.run:main'

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 120

[tool.flake8]
max-line-length = 120
extend-ignore = ["E203", "E402"]

[tool.isort]
profile = "black"
line_length = 120
include_trailing_comma = true

[tool.mypy]
plugins = ["mypy_django_plugin.main"]
disallow_untyped_defs = true
disallow_incomplete_defs = true
check_untyped_defs = true
warn_redundant_casts = true
warn_unused_ignores = true
warn_return_any = true
warn_unreachable = true
show_column_numbers = true

[[tool.mypy.overrides]]
module = "tekore.*"
ignore_missing_imports = true

[tool.django-stubs]
django_settings_module = "mottle.settings"

[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "mottle.settings"
