# Generated by Django 5.0.3 on 2024-03-28 17:24

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SpotifyAuth",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("redirect_uri", models.CharField(max_length=500, null=True)),
                ("state", models.CharField(max_length=100, unique=True)),
                ("access_token", models.CharField(max_length=500, null=True)),
                ("refresh_token", models.CharField(max_length=300, null=True)),
                ("expires_at", models.DateTimeField(null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
