# Generated by Django 5.0.4 on 2024-06-05 07:04

import uuid

import django.db.models.deletion
from django.apps.registry import Apps
from django.db import migrations, models
from django.db.backends.base.schema import BaseDatabaseSchemaEditor


def create_watch_configs(apps: Apps, _: BaseDatabaseSchemaEditor) -> None:
    Playlist = apps.get_model("web", "Playlist")
    PlaylistWatchConfig = apps.get_model("web", "PlaylistWatchConfig")

    for playlist in Playlist.objects.all():
        for watched_playlist in playlist.watched_playlists.all():
            PlaylistWatchConfig.objects.create(watching_playlist=playlist, watched_playlist=watched_playlist)


def delete_spotify_auths(apps: Apps, _: BaseDatabaseSchemaEditor) -> None:
    SpotifyAuth = apps.get_model("web", "SpotifyAuth")
    SpotifyAuth.objects.all().delete()


def delete_sessions(apps: Apps, _: BaseDatabaseSchemaEditor) -> None:
    Session = apps.get_model("sessions", "Session")
    Session.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0003_watch_playlists"),
    ]

    operations = [
        migrations.RunPython(delete_sessions),
        migrations.RunPython(delete_spotify_auths),
        migrations.CreateModel(
            name="SpotifyAuthRequest",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("state", models.CharField(max_length=50, unique=True)),
                ("redirect_uri", models.CharField(max_length=100, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.RemoveField(
            model_name="spotifyauth",
            name="redirect_uri",
        ),
        migrations.RemoveField(
            model_name="spotifyauth",
            name="state",
        ),
        migrations.AddField(
            model_name="spotifyauth",
            name="spotify_user",
            field=models.OneToOneField(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="spotify_auth",
                to="web.spotifyuser",
            ),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="PlaylistWatchConfig",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("auto_accept_updates", models.BooleanField(default=False)),
                ("tracks_ignored", models.JSONField(null=True)),
                (
                    "watched_playlist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="configs_as_watched",
                        to="web.playlist",
                    ),
                ),
                (
                    "watching_playlist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="configs_as_watching",
                        to="web.playlist",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.RunPython(create_watch_configs),
        migrations.RemoveField(
            model_name="playlist",
            name="watched_playlists",
        ),
    ]
