# Generated by Django 5.0.4 on 2024-06-07 08:59

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0004_refactor_for_autoaccept"),
    ]

    operations = [
        migrations.CreateModel(
            name="Artist",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("spotify_id", models.CharField(max_length=32, unique=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="playlistwatchconfig",
            name="albums_ignored",
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name="playlistupdate",
            name="source_artist",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="provided_updates_artist",
                to="web.playlist",
            ),
        ),
        migrations.AlterField(
            model_name="playlistupdate",
            name="source_playlist",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="provided_updates_playlist",
                to="web.playlist",
            ),
        ),
        migrations.AlterField(
            model_name="playlistwatchconfig",
            name="watched_playlist",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="configs_as_watched_playlist",
                to="web.playlist",
            ),
        ),
        migrations.AddConstraint(
            model_name="playlistupdate",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("source_playlist__isnull", False), ("source_artist__isnull", False), _connector="OR"),
                    models.Q(("source_artist__isnull", False), ("source_playlist__isnull", False), _negated=True),
                ),
                name="source_playlist_or_artist",
            ),
        ),
        migrations.AddField(
            model_name="playlistwatchconfig",
            name="watched_artist",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="configs_as_watched_artist",
                to="web.artist",
            ),
        ),
        migrations.AddConstraint(
            model_name="playlistwatchconfig",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("watched_playlist__isnull", False), ("watched_artist__isnull", False), _connector="OR"),
                    models.Q(("watched_artist__isnull", False), ("watched_playlist__isnull", False), _negated=True),
                ),
                name="watched_playlist_or_artist",
            ),
        ),
    ]
