# Generated by Django 5.0.4 on 2024-06-24 06:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0005_watch_artists"),
    ]

    operations = [
        migrations.AlterField(
            model_name="playlistupdate",
            name="source_artist",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="provided_updates_artist",
                to="web.artist",
            ),
        ),
    ]
