# Generated by Django 5.0.4 on 2024-08-03 17:41

from django.apps.registry import Apps
from django.db import migrations, models
from django.db.backends.base.schema import BaseDatabaseSchemaEditor


def set_token_scope(apps: Apps, _: BaseDatabaseSchemaEditor) -> None:
    SpotifyAuth = apps.get_model("web", "SpotifyAuth")
    SpotifyAuth.objects.update(
        token_scope=[
            "playlist-read-private",
            "playlist-read-collaborative",
            "playlist-modify-private",
            "playlist-modify-public",
            "user-follow-read",
            "user-follow-modify",
            "user-read-email",
            "ugc-image-upload",
        ]
    )


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0006_fix_playlistupdate_source_artist"),
    ]

    operations = [
        migrations.AddField(
            model_name="spotifyauth",
            name="token_scope",
            field=models.JSONField(default=[]),
            preserve_default=False,
        ),
        migrations.RunPython(set_token_scope),
    ]
