# Generated by Django 5.0.9 on 2024-11-15 06:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0007_spotifyauth_token_scope"),
    ]

    operations = [
        migrations.AlterField(
            model_name="playlistupdate",
            name="update_hash",
            field=models.CharField(max_length=64),
        ),
        migrations.AddConstraint(
            model_name="playlistupdate",
            constraint=models.UniqueConstraint(
                fields=("target_playlist", "update_hash"), name="unique_target_playlist_update_hash"
            ),
        ),
    ]
