# Generated by Django 5.0.9 on 2024-12-29 20:00

import django.contrib.gis.db.models.fields
from django.db import migrations, models

import web.models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0009_events"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="geolocation",
            field=django.contrib.gis.db.models.fields.PointField(geography=True, null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name="eventupdate",
            name="changes",
            field=models.JSONField(
                decoder=web.models.EventUpdateChangesJSONDecoder,
                encoder=web.models.EventUpdateChangesJSONEncoder,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="spotifyuser",
            name="location",
            field=django.contrib.gis.db.models.fields.PointField(geography=True, null=True, srid=4326),
        ),
    ]
