# Generated by Django 5.0.9 on 2025-02-09 15:02

import uuid

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.apps.registry import Apps
from django.db import migrations, models
from django.db.backends.base.schema import BaseDatabaseSchemaEditor


def create_users(apps: Apps, _: BaseDatabaseSchemaEditor) -> None:
    User = apps.get_model("web", "User")
    SpotifyUser = apps.get_model("web", "SpotifyUser")

    for spotify_user in SpotifyUser.objects.all():
        User.objects.create(
            spotify_user=spotify_user,
            playlist_notifications=True,
            release_notifications=False,
            event_notifications=False,
            location=spotify_user.location,
            event_distance_threshold=None,
        )


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0009_events"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("playlist_notifications", models.BooleanField(default=True)),
                ("release_notifications", models.BooleanField(default=False)),
                ("event_notifications", models.BooleanField(default=False)),
                ("location", django.contrib.gis.db.models.fields.PointField(geography=True, null=True, srid=4326)),
                ("event_distance_threshold", models.FloatField(null=True)),
                (
                    "spotify_user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, related_name="user", to="web.spotifyuser"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.RunPython(create_users),
        migrations.RemoveField(
            model_name="spotifyuser",
            name="location",
        ),
    ]
